### ISSUE TITLE
HubProxy.Call inside of a Client SubscribeOn callback removes the Subscription from the Hub

### ISSUE THREAD

**Issue by seantarogers** [AndreasBieber/SignalR.Client.TypedHubProxy#8]
Hi,

I am using V 3.0.0.0 of the SignalR.Client.TypedHubProxy in a windows service that is a subscriber of notifications from another windows service containing a hub.

The problem is that my hubProxy subscription is lost if I call back to the hub inside the subscription.  It does however work if I use the async signature.

Here are the details:

The subscriber subscribes like so:
 
       hubProxy.SubscribeOn<MyDto>(hub => hub.PublishAttachment, dto =>
            {
                   //do some stuff in a database
                  ///send a success flag back to the hub
                  hubProxy.Call(hub => hub.ReceiveAttachmentResult(result));
            });

This works the first time through and then the subscription is lost when i try and publish a second message from the hub.  The hub publishes again and nothing is picked up on the client.

1. if i comment out the following line inside the subscription - the subscription does persist between messages

                //  hubProxy.Call(hub => hub.ReceiveAttachmentResult(result));

2. If I replace that line with the async signature - the subscription also persists between messages

                hubProxy.CallAsync(hub => hub.ReceiveAttachmentResult(result));

Thanks, really like the library btw

**Comment by AndreasBieber** [comment]
Hi Sean,

i can't reproduce this problem, neither with v3.0.0 nor v3.0.1. Could you provide a sample project?

**Comment by AndreasBieber** [comment]
Hi Sean,

i was able to reproduce your problem. I figured out that this is a known behavior from SignalR and is by design (see https://github.com/SignalR/SignalR/issues/2153). In case that you're waiting for a response inside of a subscription-callback, a deadlock occurs in SignalR.

So the solution is, as you've already figured out, that you should only use (await) async-methods inside of your callback-methods:

```csharp
hubProxy.SubscribeOn<MyDto>(hub => hub.PublishAttachment, async dto =>
{
    // do some stuff in database
    // send success flag back to the hub
    await hubProxy.CallAsync(hub => hub.ReceiveAttachmentResult(result));
});
```

The sync-methods should only be used from outside:

```csharp
hubProxy.SubscribeOn<MyDto>(hub => hub.PublishAttachment, async dto =>
{
    // do some stuff in database
});

// Sync-Call
hubProxy.Call(hub => hub.ReceiveAttachmentResult(result));
```

I've decided to remove the sync-calls from TypedHubProxy in the next release, because SignalR is also not providing any sync-calls and to avoid that other consumers of TypedHubProxy also encounter this problem.

Hope this helps ...

Cheers,
 Andreas

**Comment by seantarogers** [comment]
thanks andreas, that makes sense.
